name: Documenter
on:
  push:
    branches: [ "master" ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  Documenter:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/julia-buildpkg@latest
      - name: Deploy package documentation
        uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
