name: TagBot
on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_tagbot]
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: bsc-quantic/Registry
