name: TagBot
on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_tagbot]
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.TAGBOT_TOKEN }}
          # ssh: ${{ secrets.DOCUMENTER_KEY }}
          registry: bsc-quantic/Registry
