name: TagBot
on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_tagbot]
jobs:
  TagBot:
    # if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # ssh: ${{ secrets.DOCUMENTER_KEY }}
          registry: bsc-quantic/Registry
